version: '3.6'

services:

  web:
    build: .
#      context: ./services/users
#      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - "5000:5000"
    # environment:
    #   - FLASK_APP=project/__init__.py
    #   - FLASK_ENV=development
