version: '3.6'

services:
  web:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=please_change_me
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
    - 80:80
    depends_on:
    - web

volumes:
  postgres_data:
