version: '3.6'

services:

  web:
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=recipe_robot.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@recipes-db:5432/recipes_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@recipes-db:5432/recipes_test
    depends_on:
      - recipes-db

  recipes-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

