version: '3.6'

services:

  web:
    build: .
    volumes:
    - '.:/usr/src/app'
    ports:
    - "5000:5000"
    environment:
    - FLASK_ENV=production
    - APP_SETTINGS=recipe_robot.config.ProductionConfig
    - DATABASE_URL=postgres://postgres:postgres@recipes-db:5432/recipes_dev
    - DATABASE_TEST_URL=postgres://postgres:postgres@recipes-db:5432/recipes_test
    depends_on:
    - recipes-db

  recipes-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
